# Generated by Django 3.1.4 on 2021-03-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=models.CharField(
                choices=[
                    ("breakfast", "orange"),
                    ("lunch", "green"),
                    ("dinner", "purple"),
                ],
                editable=False,
                max_length=10,
            ),
        ),
    ]
