# Generated by Django 3.1.4 on 2021-03-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0002_auto_20210307_1219"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="value",
            field=models.CharField(
                choices=[
                    ("breakfast", "breakfast"),
                    ("lunch", "lunch"),
                    ("dinner", "dinner"),
                ],
                default="",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=models.CharField(
                choices=[
                    ("breakfast", "orange"),
                    ("lunch", "green"),
                    ("dinner", "purple"),
                ],
                max_length=10,
            ),
        ),
    ]
