# Generated by Django 3.1.4 on 2021-03-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0003_auto_20210307_1224"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=models.CharField(max_length=10, verbose_name="Color"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                max_length=25, unique=True, verbose_name="Visible name"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="value",
            field=models.CharField(
                max_length=10, unique=True, verbose_name="Value"
            ),
        ),
    ]
