# Generated by Django 3.1.4 on 2021-03-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='ingredients', through='recipe.RecipeIngredient', to='recipe.Ingredient'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='weight',
            field=models.PositiveSmallIntegerField(default=0, help_text='Add needed weight for the recipe', verbose_name='ingredient weight'),
        ),
    ]
