# Generated by Django 3.1.4 on 2021-03-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0005_auto_20210307_1308"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="color",
            field=models.CharField(max_length=10, verbose_name="Color"),
        ),
        migrations.DeleteModel(
            name="Color",
        ),
    ]
