# Generated by Django 3.1.4 on 2021-03-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0006_auto_20210307_1310"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="tag",
            field=models.ManyToManyField(
                related_name="recipes", to="recipe.Tag"
            ),
        ),
    ]
