# Generated by Django 3.1.4 on 2021-03-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_auto_20210301_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.PositiveSmallIntegerField(default=10, help_text='Add cook time in minutes', verbose_name='cook time'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='weight',
            field=models.PositiveSmallIntegerField(default=10, help_text='Add needed weight for the recipe', verbose_name='ingredient weight'),
        ),
    ]
