# Generated by Django 3.1.4 on 2021-03-07 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0007_auto_20210307_2116"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeTags",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipetag",
                        to="recipe.recipe",
                        verbose_name="Название рецепта",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipetag",
                        to="recipe.tag",
                        verbose_name="Название тэга",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тэги рецепта",
                "verbose_name_plural": "Тэги рецепта",
                "unique_together": {("recipe", "tag")},
            },
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="tag",
            field=models.ManyToManyField(
                related_name="recipes",
                through="recipe.RecipeTags",
                to="recipe.Tag",
            ),
        ),
    ]
