# Generated by Django 3.1.4 on 2021-03-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0008_auto_20210307_2316"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="tag",
            field=models.ManyToManyField(
                related_name="recipes",
                through="recipe.RecipeTags",
                to="recipe.Tag",
            ),
        ),
    ]
