# Generated by Django 3.1.4 on 2021-03-07 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0009_recipe_tag"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipetags",
            options={
                "verbose_name": "Recipe tags",
                "verbose_name_plural": "Recipe tags",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "Tag", "verbose_name_plural": "Tags"},
        ),
        migrations.AlterField(
            model_name="recipetags",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipetag",
                to="recipe.recipe",
                verbose_name="Recipe title",
            ),
        ),
        migrations.AlterField(
            model_name="recipetags",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipetag",
                to="recipe.tag",
                verbose_name="Tag name",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="recipetags",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="recipetags",
            constraint=models.UniqueConstraint(
                fields=("recipe", "tag"), name="recipetag_unique"
            ),
        ),
    ]
